const express = require('express')
const path = require('path')
const app = express()
const port = 3000
const viewsDir = path.join(__dirname, 'views')
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(express.static(path.join(__dirname, './public')))
app.get('/', (req, res) => res.sendFile(path.join(viewsDir, 'index.html')))
app.listen(port, () => console.log(`Example app listening on port ${port}!`))